/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceAssuranceRouteImport } from './routes/_workspace.assurance'
import { Route as WorkspaceCustodyRouteImport } from './routes/_workspace.custody'
import { Route as WorkspaceHandlersRouteImport } from './routes/_workspace.handlers'
import { Route as WorkspaceIntakeRouteImport } from './routes/_workspace.intake'
import { Route as WorkspaceRecoveryRouteImport } from './routes/_workspace.recovery'
import { Route as PSerialRouteImport } from './routes/p.$serial'
import { Route as WorkspaceBatchesIndexRouteImport } from './routes/_workspace.batches.index'
import { Route as WorkspaceBatchesBatchIdRouteImport } from './routes/_workspace.batches.$batchId'
import { Route as WorkspaceDevicesIndexRouteImport } from './routes/_workspace.devices.index'
import { Route as WorkspaceDevicesDeviceIdRouteImport } from './routes/_workspace.devices.$deviceId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAssuranceRoute = WorkspaceAssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCustodyRoute = WorkspaceCustodyRouteImport.update({
  id: '/custody',
  path: '/custody',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceHandlersRoute = WorkspaceHandlersRouteImport.update({
  id: '/handlers',
  path: '/handlers',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceIntakeRoute = WorkspaceIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRecoveryRoute = WorkspaceRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => WorkspaceRoute,
} as any)
const PSerialRoute = PSerialRouteImport.update({
  id: '/p/$serial',
  path: '/p/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceBatchesIndexRoute = WorkspaceBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBatchesBatchIdRoute = WorkspaceBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDevicesIndexRoute = WorkspaceDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDevicesDeviceIdRoute =
  WorkspaceDevicesDeviceIdRouteImport.update({
    id: '/devices/$deviceId',
    path: '/devices/$deviceId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/assurance': typeof WorkspaceAssuranceRoute
  '/custody': typeof WorkspaceCustodyRoute
  '/handlers': typeof WorkspaceHandlersRoute
  '/intake': typeof WorkspaceIntakeRoute
  '/recovery': typeof WorkspaceRecoveryRoute
  '/p/$serial': typeof PSerialRoute
  '/batches/$batchId': typeof WorkspaceBatchesBatchIdRoute
  '/devices/$deviceId': typeof WorkspaceDevicesDeviceIdRoute
  '/batches/': typeof WorkspaceBatchesIndexRoute
  '/devices/': typeof WorkspaceDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/assurance': typeof WorkspaceAssuranceRoute
  '/custody': typeof WorkspaceCustodyRoute
  '/handlers': typeof WorkspaceHandlersRoute
  '/intake': typeof WorkspaceIntakeRoute
  '/recovery': typeof WorkspaceRecoveryRoute
  '/p/$serial': typeof PSerialRoute
  '/': typeof WorkspaceIndexRoute
  '/batches/$batchId': typeof WorkspaceBatchesBatchIdRoute
  '/devices/$deviceId': typeof WorkspaceDevicesDeviceIdRoute
  '/batches': typeof WorkspaceBatchesIndexRoute
  '/devices': typeof WorkspaceDevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/assurance': typeof WorkspaceAssuranceRoute
  '/_workspace/custody': typeof WorkspaceCustodyRoute
  '/_workspace/handlers': typeof WorkspaceHandlersRoute
  '/_workspace/intake': typeof WorkspaceIntakeRoute
  '/_workspace/recovery': typeof WorkspaceRecoveryRoute
  '/p/$serial': typeof PSerialRoute
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/batches/$batchId': typeof WorkspaceBatchesBatchIdRoute
  '/_workspace/devices/$deviceId': typeof WorkspaceDevicesDeviceIdRoute
  '/_workspace/batches/': typeof WorkspaceBatchesIndexRoute
  '/_workspace/devices/': typeof WorkspaceDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance'
    | '/custody'
    | '/handlers'
    | '/intake'
    | '/recovery'
    | '/p/$serial'
    | '/batches/$batchId'
    | '/devices/$deviceId'
    | '/batches/'
    | '/devices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/assurance'
    | '/custody'
    | '/handlers'
    | '/intake'
    | '/recovery'
    | '/p/$serial'
    | '/'
    | '/batches/$batchId'
    | '/devices/$deviceId'
    | '/batches'
    | '/devices'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/assurance'
    | '/_workspace/custody'
    | '/_workspace/handlers'
    | '/_workspace/intake'
    | '/_workspace/recovery'
    | '/p/$serial'
    | '/_workspace/'
    | '/_workspace/batches/$batchId'
    | '/_workspace/devices/$deviceId'
    | '/_workspace/batches/'
    | '/_workspace/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  PSerialRoute: typeof PSerialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/assurance': {
      id: '/_workspace/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof WorkspaceAssuranceRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/custody': {
      id: '/_workspace/custody'
      path: '/custody'
      fullPath: '/custody'
      preLoaderRoute: typeof WorkspaceCustodyRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/handlers': {
      id: '/_workspace/handlers'
      path: '/handlers'
      fullPath: '/handlers'
      preLoaderRoute: typeof WorkspaceHandlersRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/intake': {
      id: '/_workspace/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof WorkspaceIntakeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/recovery': {
      id: '/_workspace/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof WorkspaceRecoveryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/p/$serial': {
      id: '/p/$serial'
      path: '/p/$serial'
      fullPath: '/p/$serial'
      preLoaderRoute: typeof PSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/batches/': {
      id: '/_workspace/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof WorkspaceBatchesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/batches/$batchId': {
      id: '/_workspace/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof WorkspaceBatchesBatchIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/devices/': {
      id: '/_workspace/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof WorkspaceDevicesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/devices/$deviceId': {
      id: '/_workspace/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof WorkspaceDevicesDeviceIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAssuranceRoute: typeof WorkspaceAssuranceRoute
  WorkspaceCustodyRoute: typeof WorkspaceCustodyRoute
  WorkspaceHandlersRoute: typeof WorkspaceHandlersRoute
  WorkspaceIntakeRoute: typeof WorkspaceIntakeRoute
  WorkspaceRecoveryRoute: typeof WorkspaceRecoveryRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceBatchesBatchIdRoute: typeof WorkspaceBatchesBatchIdRoute
  WorkspaceDevicesDeviceIdRoute: typeof WorkspaceDevicesDeviceIdRoute
  WorkspaceBatchesIndexRoute: typeof WorkspaceBatchesIndexRoute
  WorkspaceDevicesIndexRoute: typeof WorkspaceDevicesIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAssuranceRoute: WorkspaceAssuranceRoute,
  WorkspaceCustodyRoute: WorkspaceCustodyRoute,
  WorkspaceHandlersRoute: WorkspaceHandlersRoute,
  WorkspaceIntakeRoute: WorkspaceIntakeRoute,
  WorkspaceRecoveryRoute: WorkspaceRecoveryRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceBatchesBatchIdRoute: WorkspaceBatchesBatchIdRoute,
  WorkspaceDevicesDeviceIdRoute: WorkspaceDevicesDeviceIdRoute,
  WorkspaceBatchesIndexRoute: WorkspaceBatchesIndexRoute,
  WorkspaceDevicesIndexRoute: WorkspaceDevicesIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
  PSerialRoute: PSerialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
