/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/_workspace.index'
import { Route as WorkspaceBatchesIndexRouteImport } from './routes/_workspace.batches.index'
import { Route as WorkspaceDevicesIndexRouteImport } from './routes/_workspace.devices.index'
import { Route as WorkspaceDevicesDeviceIdRouteImport } from './routes/_workspace.devices.$deviceId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceBatchesIndexRoute = WorkspaceBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDevicesIndexRoute = WorkspaceDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDevicesDeviceIdRoute =
  WorkspaceDevicesDeviceIdRouteImport.update({
    id: '/devices/$deviceId',
    path: '/devices/$deviceId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WorkspaceIndexRoute
  '/devices/$deviceId': typeof WorkspaceDevicesDeviceIdRoute
  '/batches/': typeof WorkspaceBatchesIndexRoute
  '/devices/': typeof WorkspaceDevicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof WorkspaceIndexRoute
  '/devices/$deviceId': typeof WorkspaceDevicesDeviceIdRoute
  '/batches': typeof WorkspaceBatchesIndexRoute
  '/devices': typeof WorkspaceDevicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/': typeof WorkspaceIndexRoute
  '/_workspace/devices/$deviceId': typeof WorkspaceDevicesDeviceIdRoute
  '/_workspace/batches/': typeof WorkspaceBatchesIndexRoute
  '/_workspace/devices/': typeof WorkspaceDevicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devices/$deviceId' | '/batches/' | '/devices/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devices/$deviceId' | '/batches' | '/devices'
  id:
    | '__root__'
    | '/_workspace'
    | '/_workspace/'
    | '/_workspace/devices/$deviceId'
    | '/_workspace/batches/'
    | '/_workspace/devices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/': {
      id: '/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/batches/': {
      id: '/_workspace/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof WorkspaceBatchesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/devices/': {
      id: '/_workspace/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof WorkspaceDevicesIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/devices/$deviceId': {
      id: '/_workspace/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof WorkspaceDevicesDeviceIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceDevicesDeviceIdRoute: typeof WorkspaceDevicesDeviceIdRoute
  WorkspaceBatchesIndexRoute: typeof WorkspaceBatchesIndexRoute
  WorkspaceDevicesIndexRoute: typeof WorkspaceDevicesIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceDevicesDeviceIdRoute: WorkspaceDevicesDeviceIdRoute,
  WorkspaceBatchesIndexRoute: WorkspaceBatchesIndexRoute,
  WorkspaceDevicesIndexRoute: WorkspaceDevicesIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
